import React, { useState } from "react";
import {
  ContractAnalysis,
  MissingClause,
  ClauseDeepDive,
  KeyObligation,
  ActionableChecklistItem,
  ClauseSeverity,
  ClauseCategory,
  RedlineClauseResult
} from "../types";
import {
  ShieldAlert,
  AlertTriangle,
  CheckCircle2,
  AlertCircle,
  FileWarning,
  Sparkles,
  Copy,
  Check,
  Download,
  Filter,
  ArrowRight,
  HelpCircle,
  Pencil,
  FileText,
  Clock,
  Layers,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  ExternalLink,
  Info
} from "lucide-react";
import confetti from "canvas-confetti";

interface ContractAnalyzerProps {
  analysis: ContractAnalysis | null;
  isLoading: boolean;
  onReAnalyze: () => void;
  documentTitle: string;
  onDirectRedlineRequest: (clause: string, instruction: string) => Promise<RedlineClauseResult>;
}

export const ContractAnalyzer: React.FC<ContractAnalyzerProps> = ({
  analysis,
  isLoading,
  onReAnalyze,
  documentTitle,
  onDirectRedlineRequest
}) => {
  const [activeSubTab, setActiveSubTab] = useState<"overview" | "missing" | "deepdive" | "obligations" | "checklist" | "redliner">("overview");
  const [severityFilter, setSeverityFilter] = useState<string>("All");
  const [categoryFilter, setCategoryFilter] = useState<string>("All");
  const [expandedClauseId, setExpandedClauseId] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<string | null>(null);
  
  // Custom Redliner state
  const [customClauseInput, setCustomClauseInput] = useState("");
  const [customInstruction, setCustomInstruction] = useState("Make mutually fair, protect customer from unlimited liability and preserve data ownership");
  const [partyPosition, setPartyPosition] = useState("Customer / Buyer");
  const [isRedliningCustom, setIsRedliningCustom] = useState(false);
  const [customRedlineResult, setCustomRedlineResult] = useState<RedlineClauseResult | null>(null);

  // Local checklist state
  const [checklist, setChecklist] = useState<ActionableChecklistItem[]>(
    analysis?.actionableChecklist || []
  );

  React.useEffect(() => {
    if (analysis?.actionableChecklist) {
      setChecklist(analysis.actionableChecklist);
    }
    if (analysis && analysis.overallRiskScore < 30) {
      confetti({
        particleCount: 50,
        spread: 60,
        origin: { y: 0.8 }
      });
    }
  }, [analysis]);

  const handleCopyText = (text: string, idKey: string) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idKey);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleToggleChecklist = (idx: number) => {
    const updated = [...checklist];
    updated[idx].status = updated[idx].status === "addressed" ? "pending" : "addressed";
    setChecklist(updated);
  };

  const handleRunCustomRedline = async () => {
    if (!customClauseInput.trim()) return;
    setIsRedliningCustom(true);
    try {
      const res = await onDirectRedlineRequest(customClauseInput, customInstruction);
      setCustomRedlineResult(res);
    } catch (e) {
      console.error(e);
    } finally {
      setIsRedliningCustom(false);
    }
  };

  const handleExportReport = () => {
    if (!analysis) return;
    const reportMd = `# LEXIMIND CONTRACT RISK & MISSING CLAUSE AUDIT REPORT
**Document:** ${documentTitle}
**Contract Type:** ${analysis.contractType}
**Overall Risk Score:** ${analysis.overallRiskScore}/100 (${analysis.riskLevel} Risk)
**Audit Date:** ${new Date().toLocaleDateString()}
**Governing Law:** ${analysis.governingLaw || "Not specified"}

---

## 1. EXECUTIVE RISK ASSESSMENT
${analysis.executiveSummary}

---

## 2. RISK BREAKDOWN METRICS
- Critical Exposure Clauses: ${analysis.riskBreakdown.criticalCount}
- Medium Risk Terms: ${analysis.riskBreakdown.mediumCount}
- Low Risk Terms: ${analysis.riskBreakdown.lowCount}
- Standard / Favorable Terms: ${analysis.riskBreakdown.favorableCount}

---

## 3. MISSING ESSENTIAL CLAUSES DETECTED (${analysis.missingClauses.length})
${analysis.missingClauses
  .map(
    (mc, i) => `### ${i + 1}. ${mc.clauseName} [${mc.importance} Importance]
**Standard Purpose:** ${mc.standardPurpose}
**Legal Risk If Missing:** ${mc.riskIfMissing}
**Suggested Standard Insertion:**
> ${mc.suggestedDraftClause}
`
  )
  .join("\n\n")}

---

## 4. CLAUSE-BY-CLAUSE REDLINING MATRIX
${analysis.clauseDeepDive
  .map(
    (c, i) => `### ${i + 1}. ${c.clauseTitle} (${c.category} - ${c.severity})
**Original Text:**
"${c.originalSnippet}"

**Legal Risk Analysis:**
${c.issueAnalysis}

**Recommended Redline Replacement:**
"${c.recommendedRedline}"

**Negotiation Strategy:**
${c.negotiationTip}
`
  )
  .join("\n\n")}

---
*Generated by LexiMind Legal Intelligence Engine*`;

    const blob = new Blob([reportMd], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `LexiMind_Contract_Audit_${documentTitle.replace(/\s+/g, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[500px] p-8 text-center bg-white rounded-2xl border border-slate-200 shadow-xs">
        <div className="relative mb-6">
          <div className="w-20 h-20 rounded-full border-4 border-indigo-100 border-t-indigo-600 animate-spin flex items-center justify-center" />
          <ShieldAlert className="w-8 h-8 text-indigo-600 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
        </div>
        <h3 className="text-xl font-bold text-slate-900 font-serif">
          Conducting Forensic Contract Audit
        </h3>
        <p className="text-sm text-slate-600 max-w-md mt-2">
          LexiMind is evaluating liability caps, indemnification reciprocity, termination rights, IP assignments, and identifying missing protective clauses...
        </p>
        <div className="mt-6 flex items-center space-x-2 text-xs font-medium text-indigo-700 bg-indigo-50 px-3 py-1.5 rounded-full border border-indigo-100">
          <Sparkles className="w-3.5 h-3.5 animate-pulse" />
          <span>Powered by Gemini 3.7 Flash Senior Legal Engine</span>
        </div>
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="p-8 bg-white rounded-2xl border border-slate-200 text-center">
        <ShieldAlert className="w-12 h-12 text-slate-400 mx-auto mb-3" />
        <h3 className="text-lg font-bold text-slate-900">No Contract Analysis Loaded</h3>
        <p className="text-sm text-slate-600 mt-1 mb-4">
          Select or upload an agreement to generate an exhaustive Risk Score and Missing Clauses report.
        </p>
        <button
          onClick={onReAnalyze}
          className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium transition-colors"
        >
          Analyze Current Document
        </button>
      </div>
    );
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return { bg: "bg-rose-500", text: "text-rose-700", ring: "ring-rose-200", badge: "bg-rose-100 text-rose-800" };
    if (score >= 55) return { bg: "bg-amber-500", text: "text-amber-700", ring: "ring-amber-200", badge: "bg-amber-100 text-amber-800" };
    if (score >= 30) return { bg: "bg-blue-500", text: "text-blue-700", ring: "ring-blue-200", badge: "bg-blue-100 text-blue-800" };
    return { bg: "bg-emerald-500", text: "text-emerald-700", ring: "ring-emerald-200", badge: "bg-emerald-100 text-emerald-800" };
  };

  const scoreTheme = getScoreColor(analysis.overallRiskScore);

  const filteredClauses = analysis.clauseDeepDive.filter((c) => {
    const matchSeverity = severityFilter === "All" || c.severity.toLowerCase().includes(severityFilter.toLowerCase());
    const matchCategory = categoryFilter === "All" || c.category === categoryFilter;
    return matchSeverity && matchCategory;
  });

  return (
    <div className="space-y-6">
      {/* Top Banner: Risk Gauge & Executive Snapshot */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 pb-6 border-b border-slate-100">
          <div className="space-y-1">
            <div className="flex items-center space-x-2">
              <span className="text-xs font-bold uppercase tracking-wider text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-md border border-indigo-100">
                Phase 7 Contract Audit
              </span>
              <span className="text-xs text-slate-600 font-medium">
                Type: {analysis.contractType}
              </span>
            </div>
            <h2 className="text-2xl font-bold text-slate-900 font-serif">
              {documentTitle}
            </h2>
            <p className="text-xs text-slate-600">
              Parties: <span className="font-semibold text-slate-800">{analysis.keyParties.partyA}</span> vs{" "}
              <span className="font-semibold text-slate-800">{analysis.keyParties.partyB}</span> • Governing Law:{" "}
              <span className="font-semibold text-slate-800">{analysis.governingLaw || "Delaware / Standard"}</span>
            </p>
          </div>

          <div className="flex items-center space-x-4 shrink-0">
            {/* Risk Gauge Metric Card */}
            <div className="flex items-center space-x-4 bg-slate-50 border border-slate-200 px-5 py-3 rounded-2xl">
              <div className="relative flex items-center justify-center">
                <svg className="w-18 h-18 -rotate-90">
                  <circle
                    cx="36"
                    cy="36"
                    r="30"
                    stroke="#e2e8f0"
                    strokeWidth="6"
                    fill="transparent"
                  />
                  <circle
                    cx="36"
                    cy="36"
                    r="30"
                    stroke="currentColor"
                    strokeWidth="6"
                    strokeDasharray={188.5}
                    strokeDashoffset={188.5 - (188.5 * analysis.overallRiskScore) / 100}
                    strokeLinecap="round"
                    className={`${scoreTheme.text} transition-all duration-1000 ease-out`}
                    fill="transparent"
                  />
                </svg>
                <div className="absolute text-center">
                  <span className="text-xl font-black text-slate-900 leading-none">
                    {analysis.overallRiskScore}
                  </span>
                  <span className="block text-[9px] font-bold text-slate-600 uppercase">/100</span>
                </div>
              </div>

              <div>
                <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-bold ${scoreTheme.badge}`}>
                  {analysis.riskLevel} Risk Posture
                </span>
                <p className="text-xs text-slate-600 mt-1 font-medium">
                  {analysis.overallRiskScore >= 75
                    ? "Severe Redlines Required"
                    : analysis.overallRiskScore >= 50
                    ? "Substantial Revisions Needed"
                    : "Low Exposure / Standard"}
                </p>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-2">
              <button
                id="export-audit-report-btn"
                onClick={handleExportReport}
                className="flex items-center justify-center space-x-1.5 px-3.5 py-2.5 rounded-xl text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 border border-slate-200 transition-colors"
                title="Download full Markdown Audit Memo"
              >
                <Download className="w-4 h-4" />
                <span>Export Audit</span>
              </button>

              <button
                id="reanalyze-contract-btn"
                onClick={onReAnalyze}
                className="flex items-center justify-center space-x-1.5 px-3.5 py-2.5 rounded-xl text-xs font-semibold text-white bg-indigo-600 hover:bg-indigo-700 shadow-xs transition-colors"
              >
                <RefreshCw className="w-4 h-4" />
                <span>Re-Audit</span>
              </button>
            </div>
          </div>
        </div>

        {/* Risk Breakdown Cards Row */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-6">
          <div className="bg-rose-50/70 border border-rose-200/80 rounded-xl p-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-rose-800">Critical Risks</span>
              <AlertTriangle className="w-4 h-4 text-rose-600" />
            </div>
            <p className="text-2xl font-black text-rose-900 mt-1">
              {analysis.riskBreakdown.criticalCount}
            </p>
            <p className="text-[11px] text-rose-700 mt-0.5">Immediate liability exposure</p>
          </div>

          <div className="bg-amber-50/70 border border-amber-200/80 rounded-xl p-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-amber-800">Missing Clauses</span>
              <FileWarning className="w-4 h-4 text-amber-600" />
            </div>
            <p className="text-2xl font-black text-amber-900 mt-1">
              {analysis.missingClauses.length}
            </p>
            <p className="text-[11px] text-amber-700 mt-0.5">Essential protections omitted</p>
          </div>

          <div className="bg-blue-50/70 border border-blue-200/80 rounded-xl p-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-blue-800">Medium/Low Terms</span>
              <Info className="w-4 h-4 text-blue-600" />
            </div>
            <p className="text-2xl font-black text-blue-900 mt-1">
              {analysis.riskBreakdown.mediumCount + analysis.riskBreakdown.lowCount}
            </p>
            <p className="text-[11px] text-blue-700 mt-0.5">Operational negotiation points</p>
          </div>

          <div className="bg-emerald-50/70 border border-emerald-200/80 rounded-xl p-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-emerald-800">Action Items</span>
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            </div>
            <p className="text-2xl font-black text-emerald-900 mt-1">
              {checklist.filter((c) => c.status === "addressed").length}/{checklist.length}
            </p>
            <p className="text-[11px] text-emerald-700 mt-0.5">Pre-signing requirements</p>
          </div>
        </div>
      </div>

      {/* Sub-Navigation Tabs */}
      <div className="flex items-center space-x-2 border-b border-slate-200 overflow-x-auto pb-1 scrollbar-none">
        <button
          onClick={() => setActiveSubTab("overview")}
          className={`flex items-center space-x-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors shrink-0 ${
            activeSubTab === "overview"
              ? "border-indigo-600 text-indigo-600"
              : "border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300"
          }`}
        >
          <FileText className="w-4 h-4" />
          <span>Executive Summary</span>
        </button>

        <button
          onClick={() => setActiveSubTab("missing")}
          className={`flex items-center space-x-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors shrink-0 ${
            activeSubTab === "missing"
              ? "border-amber-600 text-amber-700"
              : "border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300"
          }`}
        >
          <AlertCircle className="w-4 h-4 text-amber-500" />
          <span>Missing Clauses ({analysis.missingClauses.length})</span>
        </button>

        <button
          onClick={() => setActiveSubTab("deepdive")}
          className={`flex items-center space-x-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors shrink-0 ${
            activeSubTab === "deepdive"
              ? "border-indigo-600 text-indigo-600"
              : "border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300"
          }`}
        >
          <ShieldAlert className="w-4 h-4 text-indigo-500" />
          <span>Clause Deep-Dive & Redlines ({analysis.clauseDeepDive.length})</span>
        </button>

        <button
          onClick={() => setActiveSubTab("obligations")}
          className={`flex items-center space-x-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors shrink-0 ${
            activeSubTab === "obligations"
              ? "border-indigo-600 text-indigo-600"
              : "border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300"
          }`}
        >
          <Clock className="w-4 h-4 text-slate-500" />
          <span>Obligations & Deadlines</span>
        </button>

        <button
          onClick={() => setActiveSubTab("checklist")}
          className={`flex items-center space-x-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors shrink-0 ${
            activeSubTab === "checklist"
              ? "border-indigo-600 text-indigo-600"
              : "border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300"
          }`}
        >
          <CheckCircle2 className="w-4 h-4 text-emerald-500" />
          <span>Signing Checklist ({checklist.length})</span>
        </button>

        <button
          onClick={() => setActiveSubTab("redliner")}
          className={`flex items-center space-x-2 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors shrink-0 ${
            activeSubTab === "redliner"
              ? "border-indigo-600 text-indigo-600"
              : "border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300"
          }`}
        >
          <Pencil className="w-4 h-4 text-purple-500" />
          <span>Interactive Clause Workbench</span>
        </button>
      </div>

      {/* ------------------------------------------------------------------ */}
      {/* TAB 1: OVERVIEW & EXECUTIVE SUMMARY */}
      {/* ------------------------------------------------------------------ */}
      {activeSubTab === "overview" && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs">
              <h3 className="text-base font-bold text-slate-900 flex items-center space-x-2">
                <FileText className="w-4 h-4 text-indigo-600" />
                <span>Executive Legal Risk Memorandum</span>
              </h3>
              <div className="mt-4 prose prose-slate text-sm text-slate-700 leading-relaxed whitespace-pre-line">
                {analysis.executiveSummary}
              </div>
            </div>

            {/* Quick Summary of Top Critical Clauses */}
            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-base font-bold text-slate-900 flex items-center space-x-2">
                  <AlertTriangle className="w-4 h-4 text-rose-600" />
                  <span>Top High-Priority Redline Alerts</span>
                </h3>
                <button
                  onClick={() => setActiveSubTab("deepdive")}
                  className="text-xs text-indigo-600 hover:text-indigo-700 font-semibold flex items-center space-x-1"
                >
                  <span>View All ({analysis.clauseDeepDive.length})</span>
                  <ArrowRight className="w-3 h-3" />
                </button>
              </div>

              <div className="space-y-3">
                {analysis.clauseDeepDive.slice(0, 3).map((clause) => (
                  <div
                    key={clause.id}
                    className="p-4 rounded-xl border border-slate-200 bg-slate-50/60 hover:bg-slate-50 transition-colors"
                  >
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="font-bold text-sm text-slate-900">{clause.clauseTitle}</span>
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                          clause.severity === "Critical Risk"
                            ? "bg-rose-100 text-rose-800"
                            : "bg-amber-100 text-amber-800"
                        }`}
                      >
                        {clause.severity}
                      </span>
                    </div>
                    <p className="text-xs text-slate-600 line-clamp-2">{clause.issueAnalysis}</p>
                    <div className="mt-2 pt-2 border-t border-slate-200/60 flex items-center justify-between text-xs">
                      <span className="text-[11px] text-slate-600 font-medium">{clause.category}</span>
                      <button
                        onClick={() => {
                          setActiveSubTab("deepdive");
                          setExpandedClauseId(clause.id);
                        }}
                        className="text-indigo-600 hover:text-indigo-700 font-semibold flex items-center space-x-1"
                      >
                        <span>See Recommended Redline</span>
                        <ArrowRight className="w-3 h-3" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right Sidebar: Key Agreement Metadata & Quick Checklist */}
          <div className="space-y-6">
            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
              <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider text-slate-600">
                Agreement Metadata
              </h3>
              <div className="space-y-3 text-xs">
                <div className="flex justify-between py-1.5 border-b border-slate-100">
                  <span className="text-slate-600">Contract Type:</span>
                  <span className="font-semibold text-slate-900">{analysis.contractType}</span>
                </div>
                <div className="flex justify-between py-1.5 border-b border-slate-100">
                  <span className="text-slate-600">Effective Date:</span>
                  <span className="font-semibold text-slate-900">{analysis.effectiveDate || "Upon Execution"}</span>
                </div>
                <div className="flex justify-between py-1.5 border-b border-slate-100">
                  <span className="text-slate-600">Term / Renewal:</span>
                  <span className="font-semibold text-slate-900 text-right max-w-[160px] truncate">
                    {analysis.termAndTermination || "3-Year Auto-Renewal"}
                  </span>
                </div>
                <div className="flex justify-between py-1.5 border-b border-slate-100">
                  <span className="text-slate-600">Governing Law:</span>
                  <span className="font-semibold text-slate-900">{analysis.governingLaw || "Delaware"}</span>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-slate-900">Pre-Signing Requirements</h3>
                <span className="text-xs text-indigo-600 font-semibold">
                  {checklist.filter((c) => c.status === "addressed").length}/{checklist.length}
                </span>
              </div>
              <div className="space-y-2">
                {checklist.slice(0, 4).map((item, idx) => (
                  <div
                    key={idx}
                    onClick={() => handleToggleChecklist(idx)}
                    className="flex items-start space-x-2.5 p-2 rounded-lg hover:bg-slate-50 cursor-pointer text-xs"
                  >
                    <div className="mt-0.5">
                      {item.status === "addressed" ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                      ) : (
                        <div className="w-4 h-4 rounded border border-slate-300 shrink-0" />
                      )}
                    </div>
                    <span className={item.status === "addressed" ? "line-through text-slate-600" : "text-slate-800"}>
                      {item.item}
                    </span>
                  </div>
                ))}
              </div>
              <button
                onClick={() => setActiveSubTab("checklist")}
                className="w-full text-center text-xs text-indigo-600 font-semibold hover:underline pt-1"
              >
                View Full Signing Checklist →
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* TAB 2: MISSING ESSENTIAL CLAUSES */}
      {/* ------------------------------------------------------------------ */}
      {activeSubTab === "missing" && (
        <div className="space-y-4">
          <div className="bg-amber-50/60 border border-amber-200 rounded-2xl p-4 flex items-start space-x-3">
            <AlertCircle className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <h4 className="text-sm font-bold text-amber-900">
                {analysis.missingClauses.length} Standard Protective Clauses are Missing from this Draft
              </h4>
              <p className="text-xs text-amber-800 mt-1">
                Omitting standard bilateral protections exposes your organization to un-capped liabilities, unilateral termination risks, and loss of intellectual property rights. You can copy the suggested standard market clauses below.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {analysis.missingClauses.map((missing, idx) => (
              <div
                key={idx}
                className="bg-white rounded-2xl border border-slate-200 p-5 shadow-xs flex flex-col justify-between space-y-4"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-sm text-slate-900 font-serif">
                      {missing.clauseName}
                    </span>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        missing.importance === "Critical"
                          ? "bg-rose-100 text-rose-800"
                          : missing.importance === "Recommended"
                          ? "bg-amber-100 text-amber-800"
                          : "bg-slate-100 text-slate-700"
                      }`}
                    >
                      {missing.importance} Priority
                    </span>
                  </div>

                  <div className="text-xs space-y-1.5">
                    <p className="text-slate-600">
                      <strong className="text-slate-800">Standard Purpose:</strong> {missing.standardPurpose}
                    </p>
                    <p className="text-rose-700 bg-rose-50/50 p-2 rounded-lg border border-rose-100">
                      <strong>Risk if Missing:</strong> {missing.riskIfMissing}
                    </p>
                  </div>
                </div>

                <div className="pt-3 border-t border-slate-100 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-[11px] font-bold text-slate-600 uppercase tracking-wider">
                      Suggested Insertion Clause
                    </span>
                    <button
                      onClick={() => handleCopyText(missing.suggestedDraftClause, `missing-${idx}`)}
                      className="flex items-center space-x-1 text-xs text-indigo-600 hover:text-indigo-700 font-medium px-2 py-1 rounded-md hover:bg-indigo-50 transition-colors"
                    >
                      {copiedIndex === `missing-${idx}` ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-600" />
                          <span className="text-emerald-600">Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          <span>Copy Clause</span>
                        </>
                      )}
                    </button>
                  </div>
                  <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-800 font-mono leading-relaxed max-h-36 overflow-y-auto">
                    {missing.suggestedDraftClause}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* TAB 3: CLAUSE DEEP-DIVE & REDLINING WORKBENCH */}
      {/* ------------------------------------------------------------------ */}
      {activeSubTab === "deepdive" && (
        <div className="space-y-4">
          {/* Filters Bar */}
          <div className="bg-white rounded-xl border border-slate-200 p-4 flex flex-wrap items-center justify-between gap-3 shadow-xs">
            <div className="flex items-center space-x-2">
              <Filter className="w-4 h-4 text-slate-600" />
              <span className="text-xs font-bold text-slate-700">Filter By Severity:</span>
              {["All", "Critical", "High", "Medium", "Low"].map((sev) => (
                <button
                  key={sev}
                  onClick={() => setSeverityFilter(sev)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-colors ${
                    severityFilter === sev
                      ? "bg-indigo-600 text-white font-semibold"
                      : "bg-slate-100 text-slate-700 hover:bg-slate-200"
                  }`}
                >
                  {sev}
                </button>
              ))}
            </div>

            <div className="flex items-center space-x-2">
              <span className="text-xs font-bold text-slate-700">Category:</span>
              <select
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
                className="text-xs bg-slate-50 border border-slate-300 rounded-lg px-2.5 py-1 text-slate-800"
              >
                <option value="All">All Categories</option>
                <option value="Liability & Indemnity">Liability & Indemnity</option>
                <option value="IP & Ownership">IP & Ownership</option>
                <option value="Termination & Breach">Termination & Breach</option>
                <option value="Confidentiality & Non-Compete">Confidentiality & Non-Compete</option>
                <option value="Dispute & Jurisdiction">Dispute & Jurisdiction</option>
                <option value="Payment & Penalties">Payment & Penalties</option>
                <option value="Compliance & Data">Compliance & Data</option>
              </select>
            </div>
          </div>

          {/* Clause Cards */}
          <div className="space-y-4">
            {filteredClauses.map((clause) => {
              const isExpanded = expandedClauseId === clause.id;
              return (
                <div
                  key={clause.id}
                  className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden transition-all"
                >
                  {/* Header */}
                  <div
                    onClick={() => setExpandedClauseId(isExpanded ? null : clause.id)}
                    className="p-5 flex items-center justify-between cursor-pointer hover:bg-slate-50/80 transition-colors"
                  >
                    <div className="flex items-center space-x-3">
                      <div
                        className={`w-3 h-3 rounded-full shrink-0 ${
                          clause.severity === "Critical Risk"
                            ? "bg-rose-500 ring-4 ring-rose-100"
                            : clause.severity === "High Risk"
                            ? "bg-amber-500 ring-4 ring-amber-100"
                            : "bg-blue-500 ring-4 ring-blue-100"
                        }`}
                      />
                      <div>
                        <div className="flex items-center space-x-2">
                          <h4 className="text-base font-bold text-slate-900 font-serif">
                            {clause.clauseTitle}
                          </h4>
                          <span className="text-[11px] px-2 py-0.5 rounded bg-slate-100 text-slate-700 border border-slate-200">
                            {clause.category}
                          </span>
                        </div>
                        <p className="text-xs text-slate-600 mt-0.5 line-clamp-1">
                          {clause.issueAnalysis}
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center space-x-3 shrink-0">
                      <span
                        className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                          clause.severity === "Critical Risk"
                            ? "bg-rose-100 text-rose-800"
                            : clause.severity === "High Risk"
                            ? "bg-amber-100 text-amber-800"
                            : "bg-blue-100 text-blue-800"
                        }`}
                      >
                        {clause.severity}
                      </span>
                      {isExpanded ? (
                        <ChevronUp className="w-5 h-5 text-slate-600" />
                      ) : (
                        <ChevronDown className="w-5 h-5 text-slate-600" />
                      )}
                    </div>
                  </div>

                  {/* Expanded Body: Side-by-side Redline & Strategy */}
                  {isExpanded && (
                    <div className="p-5 pt-0 border-t border-slate-100 space-y-5 bg-slate-50/40">
                      {/* Legal Exposure Analysis */}
                      <div className="bg-rose-50/70 border border-rose-200/80 rounded-xl p-4 text-xs space-y-1">
                        <span className="font-bold text-rose-900 flex items-center space-x-1.5">
                          <AlertTriangle className="w-4 h-4 text-rose-600" />
                          <span>Forensic Risk Breakdown:</span>
                        </span>
                        <p className="text-rose-800 leading-relaxed pt-1">{clause.issueAnalysis}</p>
                      </div>

                      {/* Side by side: Original vs Redline */}
                      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                        {/* Original Snippet */}
                        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-2xs space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="text-[11px] font-bold text-rose-700 uppercase tracking-wider flex items-center space-x-1">
                              <span className="w-2 h-2 rounded-full bg-rose-500 inline-block" />
                              <span>Original Clause (Flawed Draft)</span>
                            </span>
                            <button
                              onClick={() => handleCopyText(clause.originalSnippet, `orig-${clause.id}`)}
                              className="text-[11px] text-slate-600 hover:text-slate-800 flex items-center space-x-1"
                            >
                              {copiedIndex === `orig-${clause.id}` ? (
                                <span className="text-emerald-600">Copied</span>
                              ) : (
                                <>
                                  <Copy className="w-3 h-3" />
                                  <span>Copy</span>
                                </>
                              )}
                            </button>
                          </div>
                          <div className="p-3 bg-rose-50/30 rounded-lg text-xs font-mono text-slate-800 border border-rose-100/80 leading-relaxed">
                            {clause.originalSnippet}
                          </div>
                        </div>

                        {/* Recommended Redline */}
                        <div className="bg-white rounded-xl border border-emerald-200 p-4 shadow-2xs space-y-2">
                          <div className="flex items-center justify-between">
                            <span className="text-[11px] font-bold text-emerald-700 uppercase tracking-wider flex items-center space-x-1">
                              <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block" />
                              <span>LexiMind Recommended Redline</span>
                            </span>
                            <button
                              onClick={() => handleCopyText(clause.recommendedRedline, `redline-${clause.id}`)}
                              className="text-[11px] text-emerald-700 hover:text-emerald-800 font-semibold flex items-center space-x-1 px-2 py-0.5 rounded bg-emerald-50"
                            >
                              {copiedIndex === `redline-${clause.id}` ? (
                                <span className="text-emerald-600">Copied!</span>
                              ) : (
                                <>
                                  <Copy className="w-3 h-3" />
                                  <span>Copy Replacement</span>
                                </>
                              )}
                            </button>
                          </div>
                          <div className="p-3 bg-emerald-50/40 rounded-lg text-xs font-mono text-emerald-950 border border-emerald-200 leading-relaxed">
                            {clause.recommendedRedline}
                          </div>
                        </div>
                      </div>

                      {/* Explanation of Change & Negotiation Tactics */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                        <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-1">
                          <span className="font-bold text-slate-900">Explanation of Modification:</span>
                          <p className="text-slate-600 leading-relaxed">{clause.explanationOfChange}</p>
                        </div>

                        <div className="bg-indigo-50/70 border border-indigo-200/80 rounded-xl p-4 space-y-1">
                          <span className="font-bold text-indigo-900 flex items-center space-x-1.5">
                            <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                            <span>Counterparty Negotiation Strategy:</span>
                          </span>
                          <p className="text-indigo-800 leading-relaxed">{clause.negotiationTip}</p>
                        </div>
                      </div>

                      {/* Launch interactive custom redline button */}
                      <div className="flex justify-end pt-2">
                        <button
                          onClick={() => {
                            setCustomClauseInput(clause.originalSnippet);
                            setActiveSubTab("redliner");
                          }}
                          className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold text-purple-700 bg-purple-50 hover:bg-purple-100 border border-purple-200 transition-colors"
                        >
                          <Pencil className="w-3.5 h-3.5" />
                          <span>Customize Redline in Interactive Workbench →</span>
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* TAB 4: OBLIGATIONS & OPERATIONAL DEADLINES */}
      {/* ------------------------------------------------------------------ */}
      {activeSubTab === "obligations" && (
        <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-4">
          <div>
            <h3 className="text-base font-bold text-slate-900 font-serif">
              Contractual Obligations & Deadlines Matrix
            </h3>
            <p className="text-xs text-slate-600 mt-0.5">
              Key affirmative covenants, reporting duties, and penalty conditions extracted from the agreement.
            </p>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="border-b border-slate-200 bg-slate-50 text-slate-700 uppercase tracking-wider font-semibold">
                  <th className="py-3 px-4">Responsible Party</th>
                  <th className="py-3 px-4">Obligation / Requirement</th>
                  <th className="py-3 px-4">Deadline or Condition</th>
                  <th className="py-3 px-4">Risk / Non-Compliance Impact</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {analysis.keyObligations.map((ob, idx) => (
                  <tr key={idx} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-3 px-4 font-bold text-slate-900 whitespace-nowrap">
                      {ob.party}
                    </td>
                    <td className="py-3 px-4 text-slate-800 font-medium">
                      {ob.obligation}
                    </td>
                    <td className="py-3 px-4 text-indigo-700 font-mono whitespace-nowrap">
                      {ob.deadlineOrCondition}
                    </td>
                    <td className="py-3 px-4 text-rose-700">
                      {ob.riskFactor}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* TAB 5: ACTIONABLE PRE-SIGNING CHECKLIST */}
      {/* ------------------------------------------------------------------ */}
      {activeSubTab === "checklist" && (
        <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-bold text-slate-900 font-serif">
                Pre-Signing Legal Checklist & Closing Conditions
              </h3>
              <p className="text-xs text-slate-600 mt-0.5">
                Mark items as addressed during your negotiation rounds prior to final execution.
              </p>
            </div>
            <div className="text-right">
              <span className="text-xs font-bold text-indigo-700 bg-indigo-50 px-3 py-1 rounded-full border border-indigo-200">
                {checklist.filter((c) => c.status === "addressed").length} of {checklist.length} Addressed
              </span>
            </div>
          </div>

          <div className="space-y-3">
            {checklist.map((item, idx) => (
              <div
                key={idx}
                onClick={() => handleToggleChecklist(idx)}
                className={`p-4 rounded-xl border transition-all cursor-pointer flex items-start justify-between space-x-4 ${
                  item.status === "addressed"
                    ? "bg-emerald-50/50 border-emerald-200 text-slate-600"
                    : "bg-white border-slate-200 hover:border-indigo-300 text-slate-900 shadow-2xs"
                }`}
              >
                <div className="flex items-start space-x-3">
                  <div className="mt-0.5 shrink-0">
                    {item.status === "addressed" ? (
                      <CheckCircle2 className="w-5 h-5 text-emerald-600" />
                    ) : (
                      <div className="w-5 h-5 rounded border-2 border-slate-300 hover:border-indigo-500 transition-colors" />
                    )}
                  </div>
                  <div>
                    <p
                      className={`text-sm font-semibold ${
                        item.status === "addressed" ? "line-through text-slate-600" : "text-slate-900"
                      }`}
                    >
                      {item.item}
                    </p>
                    <span className="inline-block text-[10px] font-bold px-2 py-0.5 rounded bg-slate-100 text-slate-600 mt-1">
                      {item.priority} Priority
                    </span>
                  </div>
                </div>

                <span
                  className={`text-xs font-bold px-2.5 py-1 rounded-md shrink-0 ${
                    item.status === "addressed"
                      ? "bg-emerald-100 text-emerald-800"
                      : "bg-slate-100 text-slate-700"
                  }`}
                >
                  {item.status === "addressed" ? "Addressed" : "Action Needed"}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* TAB 6: INTERACTIVE CUSTOM REDLINER WORKBENCH */}
      {/* ------------------------------------------------------------------ */}
      {activeSubTab === "redliner" && (
        <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-xs space-y-6">
          <div>
            <h3 className="text-base font-bold text-slate-900 font-serif flex items-center space-x-2">
              <Pencil className="w-4 h-4 text-purple-600" />
              <span>Interactive Custom Clause Redlining Engine</span>
            </h3>
            <p className="text-xs text-slate-600 mt-0.5">
              Paste any clause from this or any other contract, configure your negotiating posture, and get instant professional replacement language, fallback terms, and commentary.
            </p>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                Paste Original Clause to Redline:
              </label>
              <textarea
                value={customClauseInput}
                onChange={(e) => setCustomClauseInput(e.target.value)}
                placeholder="e.g. Customer shall defend, indemnify, and hold harmless Provider from any and all claims... Provider liability shall not exceed one month fees..."
                className="w-full h-32 p-3 text-xs font-mono bg-slate-50 border border-slate-300 rounded-xl focus:ring-2 focus:ring-purple-500 focus:outline-hidden"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Your Client Role / Position:
                </label>
                <input
                  type="text"
                  value={partyPosition}
                  onChange={(e) => setPartyPosition(e.target.value)}
                  placeholder="e.g. Customer, Enterprise Buyer, Executive Employee, Licensee"
                  className="w-full p-2.5 text-xs bg-slate-50 border border-slate-300 rounded-lg text-slate-800"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Negotiation Goal / Specific Mandate:
                </label>
                <input
                  type="text"
                  value={customInstruction}
                  onChange={(e) => setCustomInstruction(e.target.value)}
                  placeholder="e.g. Mutual 12-month liability cap, remove AI training rights, add 30-day cure period"
                  className="w-full p-2.5 text-xs bg-slate-50 border border-slate-300 rounded-lg text-slate-800"
                />
              </div>
            </div>

            <div className="flex justify-end">
              <button
                onClick={handleRunCustomRedline}
                disabled={isRedliningCustom || !customClauseInput.trim()}
                className="flex items-center space-x-2 px-5 py-2.5 bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white rounded-xl text-xs font-bold shadow-xs transition-colors"
              >
                {isRedliningCustom ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>Synthesizing Legal Redline...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 text-amber-300" />
                    <span>Generate Market-Standard Redline</span>
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Redline Result Box */}
          {customRedlineResult && (
            <div className="p-5 bg-purple-50/40 border border-purple-200 rounded-2xl space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="text-sm font-bold text-purple-950 font-serif">
                  Proposed Redline Replacement
                </h4>
                <button
                  onClick={() => handleCopyText(customRedlineResult.proposedRedline, "custom-res")}
                  className="text-xs text-purple-700 hover:text-purple-900 font-semibold flex items-center space-x-1 px-2.5 py-1 rounded bg-purple-100/80"
                >
                  {copiedIndex === "custom-res" ? (
                    <span className="text-emerald-700">Copied!</span>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Language</span>
                    </>
                  )}
                </button>
              </div>

              <div className="p-4 bg-white rounded-xl border border-purple-200 font-mono text-xs text-slate-900 leading-relaxed shadow-2xs">
                {customRedlineResult.proposedRedline}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-1.5">
                  <span className="font-bold text-emerald-800">Protections Gained:</span>
                  <ul className="list-disc pl-4 space-y-1 text-slate-700">
                    {customRedlineResult.protectionsGained.map((p, i) => (
                      <li key={i}>{p}</li>
                    ))}
                  </ul>
                </div>

                <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-1.5">
                  <span className="font-bold text-amber-800">Fallback Compromise Position:</span>
                  <p className="text-slate-700 font-mono text-[11px] bg-slate-50 p-2 rounded border border-slate-200">
                    {customRedlineResult.fallbackPosition}
                  </p>
                </div>
              </div>

              <div className="bg-white rounded-xl border border-slate-200 p-4 text-xs space-y-1">
                <span className="font-bold text-slate-900">Tactical Commentary for Counterparty:</span>
                <p className="text-slate-700 leading-relaxed">
                  {customRedlineResult.commentaryForCounterparty}
                </p>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
